name: Deploy to Environment

# Triggers, on specific branches
on:
  push:
    branches:
      - main
      - release
      - develop


# Running on one runner:      
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: NP
    env:
      # PROJECT NAME which is basis of resource names.
      PROJECT_NAME: 'BASALT'
      # REPO #1 (SRC) INFO
      REPO_NAME_SRC: ${{ github.repository }}
      # REPO #2 (LIB) INFO (FOR REUSEABLE PIPELINE RESOURCES)
      REPO_NAME_LIB: 'skysgh/resources.deployments.lib'
      # BRANCH INFO
      BRANCH: ${{ github.ref }}
      BRANCH_ID: '000'
      # ENVIRONMANT INFO: it's either BT, DT, ST, UT, IT, TR, PP, PR
      ENVIRONMENT_ID: ${{vars.ENVIRONMENT_ID}}  
      # DEFINE REPO CONSTANTS
      # AZURE CREDENTIALS INFO:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.NP_AZURE_SUBSCRIPTION_ID }}
      ENTRA_APP_CLIENT_ID: ${{ secrets.NP_ENTRA_APP_CLIENT_ID }}
      ENTRA_APP_CLIENT_SECRET: ${{ secrets.NP_ENTRA_APP_CLIENT_SECRET }}
      AZURE_ENTRA_APP_CLIENT_CRED: | 
        ${{ secrets.NP_ENTRA_APP_CLIENT_CREDS }}
      NODE_VERSION: 20.11.0
      ACTIONS_STEP_DEBUG: 'true'
      ACTIONS_RUNNER_DEBUG: 'true'
      PROJECT_SUBDIR: 'SOURCE/App.Service.Client.Web/'
      # make it available to params file:
      AZURE_LOCATION_1_ID: ${{ vars.AZURE_LOCATION_1_ID }}
      AZURE_LOCATION_2_ID: ${{ vars.AZURE_LOCATION_2_ID }}
      AZURE_LOCATION_3_ID: ${{ vars.AZURE_LOCATION_3_ID }}
    steps:

      # print out Inor about source:
      - name: Show Environment Info
        run: echo ${{env.REPO_NAME_SRC}}


    #   Already done.
    #   # Checkout code from *this* repo
    #   # onto runner (not target SWA...)
    #   # without giving directory, so default:
    #   - name: Checkout Project Repo
    #     uses: actions/checkout@v2
    #     with:
    #       repository: ${{env.REPO_NAME_SRC}}
  

      
      - name: "Summarise Context Before Starting"
        run: |
          echo "Misc Checks"
          echo "======================"
          echo "Syntax a.............: '${PROJECT_SUBDIR}'"
          echo "Syntax b.............: '${{env.PROJECT_SUBDIR}}'"
          echo "Initiator"
          echo "======================"
          echo "Actor................: '${GITHUB_ACTOR}'"
          echo "Event................: '${GITHUB_EVENT_NAME}'"
          echo " "
          echo "Workspace Directories"
          echo "======================"
          echo "Home.................: '${HOME}'"
          echo "Workspace............: '${GITHUB_WORKSPACE}'"
          echo " "
          echo "Libraries"
          echo "======================"
          echo "Repo.Lib.............: '${{env.REPO_NAME_LIB}}'"
          echo " "
          echo "Repo Branch"
          echo "=================="
          echo "Repo.Scr.............: '${{env.GITHUB_REPOSITORY}}'"
          echo "Branch.Name..........: '${{env.BRANCH}}'"
          echo "Branch.Ref...........: '${{github.GITHUB_REF}}'"
          echo "Branch.Number........: '${{env.BRANCH_ID}}'"
          echo "Token................: '${{secrets.GITHUB_TOKEN}}'"
          echo " "
          echo "Env"
          echo "======================"
          echo "Env.Id...............: '${{env.ENVIRONMENT_ID}}'"
          echo " "
          echo "Azure"
          echo "======================"
          echo "Azure.SubscriptionId.: '${{ secrets.NP_AZURE_SUBSCRIPTION_ID }}'"
          echo "Azure.Location.1.....: '${{ env.AZURE_LOCATION_1_ID }}'"
          echo "Azure.Location.2.....: '${{ env.AZURE_LOCATION_2_ID }}'"
          echo "Azure.Location.3.....: '${{ env.AZURE_LOCATION_3_ID }}'"
          echo " "
          echo "Entra"
          echo "======================"
          echo "Entra.TenantId.......: '${{ secrets.NP_ENTRA_TENANT_ID }}'"
          echo "Entra.AppClientId....: '${{ secrets.NP_ENTRA_APP_CLIENT_ID }}'"
          echo "Entra.AppClientSecret: '${{ secrets.NP_ENTRA_APP_CLIENT_SECRET }}'"
          echo "Entra.AppClient Creds: '${{ secrets.NP_AZURE_ENTRA_APP_CLIENT_CREDS }}'"
          echo " "

      # Cheout this repo:
      # onto runner (not target SWA...)
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      # Checkout code from *lib* repo
      # to a directory parallel to this repo's code
      - name: Checkout Library Repo
        uses: actions/checkout@v4
        with:
          repository: ${{env.REPO_NAME_LIB}}
          path: './DeploymentLib'

#      NOTE: this has been moved out of yaml.
#      - name: Ensure Resource Group(s)
#        uses: azure/arm-deploy@v1
#        with:
#          scope: subscription
#          region: ${{ vars.AZURE_LOCATION_1_ID }}
#          subscriptionId: ${{ secrets.NP_AZURE_SUBSCRIPTION_ID }}
#          #resourceGroupName: ${{ env.RG_NAME }}
#          template: ".github/workflows/resource-group.bicep"
#          parameters: "resourceGroupName=${{ env.RG_NAME }} resourceGroupLocation=${{ vars.AZURE_LOCATION_1_ID }}"
#          failOnStdErr: false


      - name: NPM - Download library of actions/yaml/etc. that can be used to build artefacts
        run: |
          # Download libraries
          npm install --prefix ${PROJECT_SUBDIR}

      - name: NPM - Build the application (Note that we are still on runner, not target swa...)
        run: |
          # Build, Compile, Package:
          npm run --prefix ${PROJECT_SUBDIR} build

      #   Not as important as I thought at first as this is iterating 
      #   over Runner (and not target SWA...)
      # - name: View contents of compiled Dist folder
      #   shell: pwsh
      #   run: |
      #     Get-ChildItem -Path "${{env.PROJECT_SUBDIR}}/dist/*.*" -Recurse -Force


      # Login to Azure, in order to manipulate remote resources
      - name: Azure Login using Action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.NP_AZURE_ENTRA_APP_CLIENT_CREDS}} 
          
# /home/runner/work/BASE.Jump.Dev.Client.Themed/BASE.Jump.Dev.Client.Themed/SOURCE/App.Service.Client.Web/dist/
      - name: Run Flow
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: ${{ vars.AZURE_LOCATION_1_ID }}
          subscriptionId: ${{ secrets.NP_AZURE_SUBSCRIPTION_ID }}
          #resourceGroupName: ${{ env.RG_NAME }}
          template: ".github/workflows/main.bicep"
          # parameters: "projectName=${{ env.PROJECT_NAME }} environmentId=BT resourceLocation=${{ vars.AZURE_LOCATION_1_ID }} repositoryUrl=https://github.com/skysgh/BASE.Jump.Dev.Client.Themed.git repositoryToken=${{secrets.GITHUB_TOKEN}} appBuildCommand='npm install && npm run build' appLocation=${{env.PROJECT_SUBDIR}} outputLocation=${{env.PROJECT_SUBDIR}}/dist/base   "
          parameters: |
            ".github/workflows/main.bicepparam" 
            repositoryToken=${{ secrets.GITHUB_TOKEN }}
          failOnStdErr: false

          
      - name: Take offline
        run: |

      - name: Move Compiled code to remote SWA directory? How?
        run: |

      - name: Wake
        run: |

      - name: Bring back online
        run: |
