name: Deploy to Environment

# Triggers, on specific branches
on:
  push:
    branches:
      - main
      - release
      - develop

# Running on one runner:      
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # REPO #1 (SRC) INFO
      REPO_NAME_SRC: $GITHUB_REPOSITORY
      # REPO #2 (LIB) INFO (FOR REUSEABLE PIPELINE RESOURCES)
      REPO_NAME_LIB: 'skysgh/resources.deployments.lib'
      # BRANCH INFO
      BRANCH: ${{ github.ref }}
      BRANCH_ID: '000'
      # ENVIRONMANT INFO: it's either BT, DT, ST, UT, IT, TR, PP, PR
      ENVIRONMENT_ID: ${{vars.ENVIRONMENT_ID}}  
      # DEFINE REPO CONSTANTS
      # AZURE CREDENTIALS INFO:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ENTRA_APP_CLIENT_ID: ${{ secrets.ENTRA_APP_CLIENT_ID }}
      ENTRA_APP_CLIENT_SECRET: ${{ secrets.ENTRA_APP_CLIENT_SECRET }}
      AZURE_ENTRA_APP_CLIENT_SECRET: ${{ secrets.ENTRA_APP_CLIENT_SECRET }}

      # AZURE RESOURCES INFO:
      AZURE_LOCATION_1: 'centralaustralia'
      AZURE_LOCATION_2: 'southeastasia'
      AZURE_LOCATION_3: 'global'
    steps:
      # Checkout code from *lib* repo
      # to a directory parallel to this repo's code
      - name: Show Environment Info
        run: echo ${{env.REPO_NAME_SRC}}

      # Checkout code from *lib* repo
      # to a directory parallel to this repo's code
      - name: Checkout Library Repo
        uses: actions/checkout@v2
        with:
          repository: ${{env.REPO_NAME_LIB}}
          path: './DeploymentLib'

    #   Already done.
    #   # Checkout code from *this* repo
    #   # without giving directory, so default:
    #   - name: Checkout Project Repo
    #     uses: actions/checkout@v2
    #     with:
    #       repository: ${{env.REPO_NAME_SRC}}
  
      - name: Determine Deployment Context
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/release' ]]; then
            echo "Setting environment to 'Prod (PR)'."
            export GITHUB_ENV='PR'
          else
            echo "Setting environment to 'Non Prod (NP)'."
            export GITHUB_ENV='NP'
          fi
          export AZURE_ENTRA_CREDS = ${{secrets.AZURE_ENTRA_APP_CLIENT_CREDS}}

      # Checkout code from *lib* repo
      # to a directory parallel to this repo's code
      
      - name: "Summarise Context Before Starting"
        run: |
          echo "Actor"
          echo "Initiator"
          echo "======================"
          echo "Actor................: '${GITHUB_ACTOR}'"
          echo "Event................: '${GITHUB_EVENT_NAME}'"
          echo ""
          echo "Directories"
          echo "======================"
          echo "Home.................: '${HOME}'"
          echo "Workspace............: '${GITHUB_WORKSPACE}'"
          echo ""
          echo "Libraries"
          echo "======================"
          echo "Repo.Lib.............: '${{env.REPO_NAME_LIB}}'"
          echo ""
          echo "Repo Branch"
          echo "=================="
          echo "Repo.Scr.............: '${{env.GITHUB_REPOSITORY}}'"
          echo "Branch.Name..........: '${{env.BRANCH}}'"
          echo "Branch.Ref...........: '${{github.GITHUB_REF}}'"
          echo "Branch.Number........: '${{env.BRANCH_ID}}'"
          echo ""
          echo "Env"
          echo "======================"
          echo "Env.Name.............: '${{env.ENVIRONMENT_NAME}}'"
          echo "Env.Id...............: '${{env.ENVIRONMENT_ID}}'"
          echo ""
          echo "Azure"
          echo "======================"
          echo "Azure.SubscriptionId.: '${{secrets.NP_AZURE_SUBSCRIPTION_ID}}'"
          echo "Azure.Location.1.....: '${{env.AZURE_LOCATION_1}}'"
          echo "Azure.Location.2.....: '${{env.AZURE_LOCATION_2}}'"
          echo "Azure.Location.3.....: '${{env.AZURE_LOCATION_3}}'"
          echo ""
          echo "Entra"
          echo "======================"
          echo "Entra.TenantId.......: '${{secrets.NP_ENTRA_TENANT_ID}}'"
          echo "Entra.AppClientId....: '${{secrets.NP_ENTRA_CLIENT_ID}}'"
          echo "Entra.AppClientSecret: '${{secrets.NP_ENTRA_CLIENT_SECRET}}'"
          echo "Entra.AppClient Creds: '${{secrets.NP_AZURE_ENTRA_CLIENT_CREDS}}'"
          echo ""
      - name: Azure Login using Action - S
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NP_AZURE_ENTRA_CLIENT_CREDS}} 
 
      - name: Ensure Resource Group(s)
        run: |
          # Your deployment commands here

      - name: Ensure Static WebSite Resource
        run: |
          # Your deployment commands here

      - name: Compile source code
        run: |

      - name: Take offline
        run: |

      - name: Deploy source code
        run: |

      - name: Wake
        run: |

      - name: Bring back online
        run: |
