
name: Deploy to Environment

# Triggers, on specific branches
on:
  push:
    branches:
      - main
      - release
      - develop
    
env:
  # Where to find reusable bicep, etc. files
  THIS_DIRECTORY: '.github/workflows'
  WORKFLOW_BICEP_DIRECTORY: '.github/workflows/bicep'
  LIB_BICEP_DIRECTORY: '.github/workflows//lib/azure/bicep' # REPO_LIB_DIR1
 
# Running on one runner:      
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: NP
    env:
      FOO: BAR
    steps:
      # ==================================================
      - name: "Summarise Context Before Starting"
        run: |
          echo "{{$env.BAR}}"

          
