name: Deploy to Environment


# Triggers, on specific branches
on:
  push:
    branches:
      - main
      - release
      - develop
    
env:
  # Where to find reusable bicep, etc. files
  THIS_DIRECTORY: '.github/workflows'
  WORKFLOW_BICEP_DIRECTORY: '.github/workflows/bicep'
  LIB_BICEP_DIRECTORY: '.github/workflows/lib/azure/bicep/recipes' # REPO_LIB_DIR1
  MAIN_BICEP_FILENAME: 'sql-server-deployment.bicep'


# Running on one runner:      
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: NP
    env:
      FOO: BAR
      # ======================================================================
      # FIXED (CONTEXT):
      # ======================================================================
      # where imported repo should go
      REPO_LIB_DIR: "./DeploymentLib"
      # File that this YAML invokes at some point, along with its params
      # MAIN_BICEP_FILENAME: 'dynamic-app-service.bicep'
      # MAIN_BICEP_PARAM_FILENAME: 'main.service-client.bicepparam'
      # ======================================================================
      # INPUTS:
      # ======================================================================
      # IMPORTANT:

      # PROJECT NAME which is basis of Azure resource names.
      PROJECT_NAME: 'BASE'
      PROJECT_SERVICE_NAME: 'SERVICE'
      # ENVIRONMANT INFO: it's either BT, DT, ST, UT, IT, TR, PP, PR
      PROJECT_ENV_ID: 'BT' # ${{vars.PROJECT_ENV_ID}}
      # Angular Code Name (affects where code ends up in dist/xxx)
      # ======================================================================

    steps:
      # ==================================================
      - name: "Summarise Context Before Starting"
        run: |
          echo "::group::Misc"
          echo "{{$env.BAR}}"
          echo "::endgroup::"

      # ==================================================
      # Checkout code from *lib* repo
      # to a directory parallel to this repo's code
      - name: Checkout Library Repo
        uses: actions/checkout@v4
        with:
          repository: ${{env.LIB_REPO_SRC_URL}}
          path: './DeploymentLib'

      # ==================================================
      # Checkout code from *this* repo
      # onto runner (not target SWA...)
      # without giving directory, so default:
      - name: Checkout this Project's Repo
        uses: actions/checkout@v4
        # Optional to specify repo:
        # with:
        #  repository: ${{env.THIS_REPO}}

      # ==================================================
      # Login to Azure, in order to manipulate remote resources
      - name: Azure Login, using Action, to enable building resources
        uses: azure/login@v2
        with:
          creds: ${{ secrets.NP_AZURE_ENTRA_APP_CLIENT_CREDS}} 
          
      # ==================================================
      - name: Run main bicep file (creating RG & WEB APP SERVER, SQL SERVER, etc.)
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: ${{ vars.AZURE_LOCATION_1_ID }}
          subscriptionId: ${{ secrets.NP_AZURE_SUBSCRIPTION_ID }}
          
          template: "${{ env.LIB_BICEP_DIRECTORY }}/${{env.MAIN_BICEP_FILENAME}}"

          # Do NOT wrap values in single quotes (only double quotes if need be)
          parameters: >
            projectName="${{ env.PROJECT_NAME }}"
            projectServiceName="${{ env.PROJECT_SERVICE_NAME }}"
            environmentId="${{ env.PROJECT_ENV_ID}}"
            resourceGroupLocationId="australiacentral" 
            sqlServerLocationId="australiacentral"
            sqlServerDbLocationId="australiacentral"
            resourceSKU=Basic

            sqlServerMinimalTlsVersion="1.3"
            sqlServerIdentityType="SystemAssigned,UserAssigned"
            sqlServerAdminUserName=${{ secrets.DB_ADMIN_NAME}}
            sqlServerAdminPassword=${{ secrets.DB_ADMIN_PWD}}
            
            sqlServerDbautoPauseDelay=2
            sqlServerDbAvailabilityZone="NoPreference"
            sqlServerDbUseFreeLimit=false
            sqlServerDbFreeLimitExhaustionBehavior="BillOverUsage"
            sqlServerDbAvailabilityZone="NoPreference"
            sqlServerDbIsLedgerOn=true
            sqlServerDbCreateMode="Create"
            sqlServerDbSampleName=""
            sqlServerDbCollation="SQL_Latin1_General_CP1_CI_AS"
            sqlServerDbCatalogCollation="DATABASE_DEFAULT"
            sqlServerDbZoneRedundant=false
            
          # Removed
          #  serverfarmsResourceLocationId="australiacentral"  
          #  sitesResourceLocationId="australiacentral" 
          #  sourcecontrolsResourceLocationId="australiacentral"
          #  webAppServicePlanSKU="F1"
          #  linuxFxVersion="DOTNETCORE|Latest"
          #  repositoryUrl="https://todo"
          #  repositoryBranch='main'
          #  repositoryToken="${{ secrets.GH_BASE_CLIENT_THEMED }}"
          #  repositorySourceLocation="/"
          failOnStdErr: false
          
