name: Deploy to Environment


# Triggers, on specific branches
on:
  push:
    branches:
      - main
      - release
      - develop
env:
  # env needs at least one line:  
  foo: bar
  
# Running on one runner:      
jobs:
  call-workflow-passing-data:
    # Invoke the callee either in same repo, or remote rempo
    # ./.github/workflows/callee.yaml
    uses: skysgh/resources.deployments.lib/.github/workflows/back-end-deployment.yaml@main
    with:
      # ======================================================================
      # RELIANT ON SECRETS
      # ======================================================================
      # NP_AZURE_ENTRA_APP_CLIENT_CREDS
      # NP_AZURE_SUBSCRIPTION_ID
      # DB_ADMIN_NAME
      # DB_ADMIN_PWD
      # ======================================================================
      # PROJECT PARAMETERS
      # ======================================================================
      # The project name, which informs naming of 
      # Azure resource groups and resource names 
      # definately changes per project.
      # Note: it could be set here, or come from GitHUb repo vars:
      PROJECT_NAME: 'BASE'
      PROJECT_SERVICE_NAME: ''
      PROJECT_DESCRIPTION: 'Creates backend RG, WEB APP SERVER, SQL SERVER, etc.'
      # ======================================================================
      # SRC PARAMETERS
      # ======================================================================
      SRC_REPO_GITHUB_USER_AND_REPO_NAME: ${{github.repository}}
      SRC_REPO_BRANCH: "main"
      SRC_REPO_SOURCE_ENTRY_FOLDER: "SOURCE/SOMETHING/TODO/..."
      # ======================================================================
      # LIB PARAMETERS
      # ======================================================================
      # LIB_REPO_GITHUB_USER_AND_REPO_NAME: "skysgh/resources.deployments.lib"
      # ======================================================================
      # AZURE PARAMETERS
      # ======================================================================
      AZURE_LOCATION_ID_0: global 
      AZURE_LOCATION_ID_1: newzealand
      AZURE_LOCATION_ID_2: australiacentral
      AZURE_LOCATION_ID_3: southeastasia
    secrets:  # inherit
      # AZURE Subcription & Access Params:
      AZURE_SUBSCRIPTION_ID: ${{secrets.NP_AZURE_SUBSCRIPTION_ID}}
      AZURE_ENTRA_APP_CLIENT_CREDS: ${{secrets.NP_AZURE_ENTRA_APP_CLIENT_CREDS}}
      # AZURE REsource Params:
      DB_ADMIN_NAME: ${{secrets.DB_ADMIN_NAME}}
      DB_ADMIN_PWD: ${{secrets.DB_ADMIN_PWD}}
