name: Build Service Client Infrasstructure and Deploy

# Triggers, on specific branches
on:
  push:
    branches:
      - main
      - release
      - develop    
env:
  # env needs at least one line:  
  foo: bar
  # DEFINE REPO CONSTANTS
  NODE_VERSION: 20.11.0
  ACTIONS_STEP_DEBUG: 'true'
  ACTIONS_RUNNER_DEBUG: 'true'  


# Running on one runner:      
jobs:
  call-workflow-passing-data:
    uses: skysgh/resources.deployments.lib/.github/workflows/front-end-deployment.yaml@main
    with:
      # ======================================================================
      # RELIANT ON SECRETS
      # ======================================================================
      # NP_AZURE_ENTRA_APP_CLIENT_CREDS
      # NP_AZURE_SUBSCRIPTION_ID
      # DB_ADMIN_NAME
      # DB_ADMIN_PWD
      # ======================================================================
      # PROJECT PARAMETERS
      # ======================================================================
      # The project name, which informs naming of 
      # Azure resource groups and resource names 
      # definately changes per project.
      # Note: it could be set here, or come from GitHUb repo vars:
      PROJECT_NAME: "BASE"
      PROJECT_SERVICE_NAME: "CORE"
      PROJECT_DESCRIPTION: "Creates front end RG, Static Web APp (SWA), etc."
      PROJECT_ENVIRONMENT_ID: 'BT'       ## ${{vars.PROJECT_ENV_ID}}
      # ======================================================================
      # SRC PARAMETERS
      # ======================================================================
      SRC_REPO_GITHUB_USER_AND_REPO_NAME: ${{github.repository}}
      SRC_GITHUB_REPO_LANDING_PAGE_URL: "https://github.com/skysgh/BASE.Jump.Dev.Client.Themed"
      SRC_REPO_BRANCH: "main"
      SRC_REPO_SOURCE_ENTRY_FOLDER: "SOURCE/App.Service.Client.Web"
      # ======================================================================
      # SWA VARIABLES
      # ======================================================================
      SWA_ANGULAR_PROJECT_NAME: 'base'
      SWA_ANGULAR_BUILD_COMMAND: 'npm install && npm run build'
      # ======================================================================
      # LIB PARAMETERS
      # ======================================================================
      # LIB_REPO_GITHUB_USER_AND_REPO_NAME: "skysgh/resources.deployments.lib"
      # ======================================================================
      # AZURE VARIABLES
      # ======================================================================
      # see: https://gist.github.com/ausfestivus/04e55c7d80229069bf3bc75870630ec8
      AZURE_LOCATION_ID: australiacentral
      AZURE_LOCATION_ID_SWA: eastasia      
      # ======================================================================
    secrets:  # inherit
      # AZURE Subcription & Access Params:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.NP_AZURE_SUBSCRIPTION_ID }}
      AZURE_ENTRA_APP_CLIENT_CREDS: ${{ secrets.NP_AZURE_ENTRA_APP_CLIENT_CREDS }}
