name: Deploy to Environment


# Triggers, on specific branches
on:
  push:
    branches:
      - main
      - release
      - develop
env:
  # ======================================================================
  # PROJECT VARIABLES
  # ======================================================================
  # The project name, which informs naming of 
  # Azure resource groups and resource names 
  # definately changes per project.
  # Note: it could be set here, or come from GitHUb repo vars:
  PROJECT_NAME: 'BASE'
  PROJECT_SERVICE_NAME: ''
  PROJECT_DESCRIPTION: 'Creates backend RG, WEB APP SERVER, SQL SERVER, etc.'
  # ======================================================================
  # SRC VARIABLES
  # ======================================================================
  SRC_REPO_GITHUB_USER_AND_REPO_NAME: ...
  SRC_REPO_BRANCH: main
  SRC_REPO_ENTRY_FOLDER: "/"
  SRC_REPO_DEPLOYMENT_DIR: "/"
  # ======================================================================
  # LIB VARIABLES
  # ======================================================================
  LIB_REPO_GITHUB_USER_AND_REPO_NAME: "skysgh/resources.deployments.lib"
  # ======================================================================

  
# Running on one runner:      
jobs:
  call-workflow-passing-data:
    # Invoke the callee either in same repo, or remote rempo
    # ./.github/workflows/callee.yaml
    uses: skysgh/resources.deployments.lib/.github/workflows/back-end-deployment.yaml@main
    with:
      foo: bar
    secrets: inherit
      # or specific ones:
      # envPAT: blah blah...
