name: Deploy to Environment


# Triggers, on specific branches
on:
  push:
    branches:
      - main
      - release
      - develop    
env:
  # Where to find reusable bicep, etc. files
  THIS_DIRECTORY: '.github/workflows'
  WORKFLOW_BICEP_DIRECTORY: '.github/workflows/bicep'
  LIB_BICEP_DIRECTORY: '.github/workflows/lib/azure/bicep/recipes' # REPO_LIB_DIR1
  MAIN_BICEP_FILENAME: 'backend-deployment.bicep'



# Running on one runner:      
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: NP
    env:
      FOO: BAR
      # ======================================================================
      # FIXED (CONTEXT):
      # ======================================================================
      # where imported repo should go
      REPO_LIB_DIR: "./DeploymentLib"
      # File that this YAML invokes at some point, along with its params
      # MAIN_BICEP_FILENAME: 'dynamic-app-service.bicep'
      # MAIN_BICEP_PARAM_FILENAME: 'main.service-client.bicepparam'
      # ======================================================================
      # INPUTS:
      # ======================================================================
      # IMPORTANT:

      # PROJECT NAME which is basis of Azure resource names.
      PROJECT_NAME: 'DINK'
      # Angular Code Name (affects where code ends up in dist/xxx)
      # ======================================================================

    steps:
      # ==================================================
      - name: "Summarise Context Before Starting"
        run: |
          echo "::group::Misc"
          echo "{{$env.BAR}}"
          echo "::endgroup::"

      # ==================================================
      # Checkout code from *lib* repo
      # to a directory parallel to this repo's code
      - name: Checkout Library Repo
        uses: actions/checkout@v4
        with:
          repository: ${{env.LIB_REPO_SRC_URL}}
          path: './DeploymentLib'

      # ==================================================
      # Checkout code from *this* repo
      # onto runner (not target SWA...)
      # without giving directory, so default:
      - name: Checkout this Project's Repo
        uses: actions/checkout@v4
        # Optional to specify repo:
        # with:
        #  repository: ${{env.THIS_REPO}}

      # ==================================================
      # Login to Azure, in order to manipulate remote resources
      - name: Azure Login, using Action, to enable building resources
        uses: azure/login@v2
        with:
          creds: ${{ secrets.NP_AZURE_ENTRA_APP_CLIENT_CREDS}} 
          
      # ==================================================
      - name: Run main bicep file (creating RG & WEB APP SERVER, SQL SERVER, etc.)
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: ${{ vars.AZURE_LOCATION_1_ID }}
          subscriptionId: ${{ secrets.NP_AZURE_SUBSCRIPTION_ID }}
          
          template: "${{ env.LIB_BICEP_DIRECTORY }}/${{env.MAIN_BICEP_FILENAME}}"
 
          # Consider: sqlServerDbResourxeLocationId: 'F1','D1','B1','B2','S1','S2'
          # Consider: sqlServerDbResourceSKU: 'Basic', 'S0', 'S1', 'S2'
          # Consider: webServerFarmsResourceSKU can't be Shared/D1 if Linux is used
          # 
          # Do NOT wrap values in single quotes (only double quotes if need be)
          # Do NOT inject blank lines.

          # "${{ env.PROJECT_ENV_ID}}"
          
          parameters: >
            buildResourceGroup=true
            projectName="${{ env.PROJECT_NAME }}"
            projectServiceName="${{ env.PROJECT_SERVICE_NAME }}"
            environmentId="NP"
            defaultResourceLocationId="australiacentral"
            webServerFarmsResourceLocationId="australiacentral"  
            webServerFarmsResourceSKU="S1"
            webSitesLinuxFxVersion="DOTNETCORE|Latest"
            webSitesSourceControlsRepositoryUrl="https://todo"
            webSitesSourceControlsRepositoryBranch='main'
            webSitesSourceControlsRepositoryToken="${{ secrets.GH_BASE_CLIENT_THEMED }}"
            webSitesSourceControlsRepositorySourceLocation="/"
            sqlServerResourceLocationId="australiacentral"
            sqlServerMinimalTlsVersion="1.3"
            sqlServerIdentityType="None"
            sqlServerAdminUserName="${{secrets.DB_ADMIN_NAME}}"
            sqlServerAdminPassword="${{secrets.DB_ADMIN_PWD}}"
            sqlServerDbResourceLocationId="australiacentral"
            sqlServerDbResourceSKU="S1"
            sqlServerDbResourceTier="Standard"
            sqlServerDbAvailabilityZone="NoPreference"
            sqlServerDbZoneRedundant=false
            sqlServerDbUseFreeLimit=false
            sqlServerDbFreeLimitExhaustionBehavior="BillOverUsage"
            sqlServerDbAutoPauseDelay=120
            sqlServerDbSampleName=""
            sqlServerDbIsLedgerOn=false
            sqlServerDbCreateMode="Default"
            sqlServerDbCollation="SQL_Latin1_General_CP1_CI_AS"
            sqlServerDbCatalogCollation="DATABASE_DEFAULT"
            sqlServerDbResourceName="Default"
            
          # Removed
          #  serverfarmsResourceLocationId="australiacentral"  
          #  sitesResourceLocationId="australiacentral" 
          #  sourcecontrolsResourceLocationId="australiacentral"
          #  webAppServicePlanSKU="F1"
          #  linuxFxVersion="DOTNETCORE|Latest"
          #  repositoryUrl="https://todo"
          #  repositoryBranch='main'
          #  repositoryToken="${{ secrets.GH_BASE_CLIENT_THEMED }}"
          #  repositorySourceLocation="/"
          failOnStdErr: false
          
